version: '3'

services:
  vistaar-db:
    image: postgres:15.3
    container_name: vistaar-db
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=vistaar
    volumes:
      - ./postgres-vistaar:/var/lib/postgresql/data
